export const CountryPhoneNumberDigit = [
  {
    name: "Afghanistan",
    code: "AF",
    file_url: "//upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
    countryCode: "+93",
    phoneNumberLength: 9,
    nationality: "Afghan",
  },
  {
    name: "Åland Islands",
    code: "AX",
    file_url: "//upload.wikimedia.org/wikipedia/commons/5/52/Flag_of_%C3%85land.svg",
    countryCode: "+358",
    phoneNumberLength: 7,
    nationality: "Åland Islander",
  },
  {
    name: "Albania",
    code: "AL",
    file_url: "//upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg",
    countryCode: "+355",
    phoneNumberLength: 9,
    nationality: "Albanian",
  },
  {
    name: "Algeria",
    code: "DZ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg",
    countryCode: "+213",
    phoneNumberLength: 9,
    nationality: "Algerian",
  },
  {
    name: "American Samoa",
    code: "AS",
    file_url: "//upload.wikimedia.org/wikipedia/commons/8/87/Flag_of_American_Samoa.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "American Samoan",
  },
  {
    name: "AndorrA",
    code: "AD",
    file_url: "//upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Andorra.svg",
    countryCode: "+376",
    phoneNumberLength: 6,
    nationality: "Andorran",
  },
  {
    name: "Angola",
    code: "AO",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Angola.svg",
    countryCode: "+244",
    phoneNumberLength: 9,
    nationality: "Angolan",
  },
  {
    name: "Anguilla",
    code: "AI",
    file_url: "//upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Anguilla.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Anguillan",
  },
  {
    name: "Antarctica",
    code: "AQ",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/b/bb/Proposed_flag_of_Antarctica_%28Graham_Bartram%29.svg",
    countryCode: "",
    phoneNumberLength: 0,
    nationality: "Antarctican",
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    countryCode: "+1",
    file_url: "//upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Antigua_and_Barbuda.svg",
    phoneNumberLength: 10,
    nationality: "Antiguan and Barbudan",
  },
  {
    name: "Argentina",
    code: "AR",
    file_url: "//upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
    countryCode: "+54",
    phoneNumberLength: 10,
    nationality: "Argentinian",
  },
  {
    name: "Armenia",
    code: "AM",
    file_url: "//upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Armenia.svg",
    countryCode: "+374",
    phoneNumberLength: 8,
    nationality: "Armenian",
  },
  {
    name: "Aruba",
    code: "AW",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Aruba.svg",
    countryCode: "+297",
    phoneNumberLength: 7,
    nationality: "Aruban",
  },
  {
    name: "Australia",
    code: "AU",
    file_url: "//upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Australia_%28converted%29.svg",
    countryCode: "+61",
    phoneNumberLength: 10,
    nationality: "Australian",
  },
  {
    name: "Austria",
    code: "AT",
    file_url: "//upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg",
    countryCode: "+43",
    phoneNumberLength: 11,
    nationality: "Austrian",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg",
    countryCode: "+994",
    phoneNumberLength: 9,
    nationality: "Azerbaijani",
  },
  {
    name: "Bahamas",
    code: "BS",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/93/Flag_of_the_Bahamas.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Bahamian",
  },
  {
    name: "Bahrain",
    code: "BH",
    file_url: "//upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg",
    countryCode: "+973",
    phoneNumberLength: 8,
    nationality: "Bahraini",
  },
  {
    name: "Bangladesh",
    code: "BD",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg",
    countryCode: "+880",
    phoneNumberLength: 10,
    nationality: "Bangladeshi",
  },
  {
    name: "Barbados",
    code: "BB",
    file_url: "//upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Barbados.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Barbadian",
  },
  {
    name: "Belarus",
    code: "BY",
    file_url: "//upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Belarus.svg",
    countryCode: "+375",
    phoneNumberLength: 9,
    nationality: "Belarusian",
  },
  {
    name: "Belgium",
    code: "BE",
    file_url: "//upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg",
    countryCode: "+32",
    phoneNumberLength: 9,
    nationality: "Belgian",
  },
  {
    name: "Belize",
    code: "BZ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/e/e7/Flag_of_Belize.svg",
    countryCode: "+501",
    phoneNumberLength: 7,
    nationality: "Belizean",
  },
  {
    name: "Benin",
    code: "BJ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Benin.svg",
    countryCode: "+229",
    phoneNumberLength: 8,
    nationality: "Beninese",
  },
  {
    name: "Bermuda",
    code: "BM",
    file_url: "//upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bermuda.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Bermudian",
  },
  {
    name: "Bhutan",
    code: "BT",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/91/Flag_of_Bhutan.svg",
    countryCode: "+975",
    phoneNumberLength: 8,
    nationality: "Bhutanese",
  },
  {
    name: "Bolivia",
    code: "BO",
    file_url: "//upload.wikimedia.org/wikipedia/commons/b/b3/Bandera_de_Bolivia_%28Estado%29.svg",
    countryCode: "+591",
    phoneNumberLength: 8,
    nationality: "Bolivian",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    file_url: "//upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg",
    countryCode: "+387",
    phoneNumberLength: 8,
    nationality: "Bosnian and Herzegovinian",
  },
  {
    name: "Botswana",
    code: "BW",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Botswana.svg",
    countryCode: "+267",
    phoneNumberLength: 8,
    nationality: "Motswana (singular), Batswana (plural)",
  },
  {
    name: "Bouvet Island",
    code: "BV",
    file_url: "//upload.wikimedia.org/wikipedia/commons/e/ee/Bouvet_Island_flagmap.png",
    countryCode: "+47",
    phoneNumberLength: 0,
    nationality: "No inhabitants, no specific nationality",
  },
  {
    name: "Brazil",
    code: "BR",
    file_url: "//upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg",
    countryCode: "+55",
    phoneNumberLength: 11,
    nationality: "Brazilian",
  },
  {
    name: "British Indian Ocean Territory",
    code: "IO",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg",
    countryCode: "+246",
    phoneNumberLength: 0,
    nationality: "British Overseas Territory (no specific nationality)",
  },
  {
    name: "Brunei Darussalam",
    code: "BN",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Brunei.svg",
    countryCode: "+673",
    phoneNumberLength: 7,
    nationality: "Bruneian",
  },
  {
    name: "Bulgaria",
    code: "BG",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg",
    countryCode: "+359",
    phoneNumberLength: 9,
    nationality: "Bulgarian",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    file_url: "//upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Burkina_Faso.svg",
    countryCode: "+226",
    phoneNumberLength: 8,
    nationality: "Burkinabé",
  },
  {
    name: "Burundi",
    code: "BI",
    file_url: "//upload.wikimedia.org/wikipedia/commons/5/50/Flag_of_Burundi.svg",
    countryCode: "+257",
    phoneNumberLength: 8,
    nationality: "Burundian",
  },
  {
    name: "Cambodia",
    code: "KH",
    file_url: "//upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Cambodia.svg",
    countryCode: "+855",
    phoneNumberLength: 8,
    nationality: "Cambodian",
  },
  {
    name: "Cameroon",
    code: "CM",
    file_url: "//upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg",
    countryCode: "+237",
    phoneNumberLength: 8,
    nationality: "Cameroonian",
  },
  {
    name: "Canada",
    code: "CA",
    file_url: "//upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Canada_%28Pantone%29.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Canadian",
  },
  {
    name: "Cape Verde",
    code: "CV",
    file_url: "//upload.wikimedia.org/wikipedia/commons/7/7d/Cape_Verde_Flag.svg",
    countryCode: "+238",
    phoneNumberLength: 7,
    nationality: "Cape Verdean",
  },
  {
    name: "Cayman Islands",
    code: "KY",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_the_Cayman_Islands.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Caymanian",
  },
  {
    name: "Central African Republic",
    code: "CF",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Central_African_Republic.svg",
    countryCode: "+236",
    phoneNumberLength: 8,
    nationality: "Central African",
  },
  {
    name: "Chad",
    code: "TD",
    file_url: "//upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Chad.svg",
    countryCode: "+235",
    phoneNumberLength: 8,
    nationality: "Chadian",
  },
  {
    name: "Chile",
    code: "CL",
    file_url: "//upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg",
    countryCode: "+56",
    phoneNumberLength: 8,
    nationality: "Chilean",
  },
  {
    name: "China",
    code: "CN",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg",
    countryCode: "+86",
    phoneNumberLength: 11,
    nationality: "Chinese",
  },
  {
    name: "Christmas Island",
    code: "CX",
    file_url: "//upload.wikimedia.org/wikipedia/commons/6/67/Flag_of_Christmas_Island.svg",
    countryCode: "+61",
    phoneNumberLength: 10,
    nationality: null,
  },
  {
    name: "Cocos (Keeling) Islands",
    code: "CC",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Cocos_%28Keeling%29_Islands.svg",
    countryCode: "+61",
    phoneNumberLength: 10,
    nationality: null,
  },
  {
    name: "Colombia",
    code: "CO",
    file_url: "//upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg",
    countryCode: "+57",
    phoneNumberLength: 10,
    nationality: "Colombian",
  },
  {
    name: "Comoros",
    code: "KM",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/94/Flag_of_the_Comoros.svg",
    countryCode: "+269",
    phoneNumberLength: 7,
    nationality: "Comoran",
  },
  {
    name: "Congo",
    code: "CG",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_the_Republic_of_the_Congo.svg",
    countryCode: "+242",
    phoneNumberLength: 9,
    nationality: "Congolese",
  },
  {
    name: "Congo, The Democratic Republic of the",
    code: "CD",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg",
    countryCode: "+243",
    phoneNumberLength: 9,
    nationality: "Congolese",
  },
  {
    name: "Cook Islands",
    code: "CK",
    file_url: "//upload.wikimedia.org/wikipedia/commons/3/35/Flag_of_the_Cook_Islands.svg",
    countryCode: "+682",
    phoneNumberLength: 5,
    nationality: "Cook Islander",
  },
  {
    name: "Costa Rica",
    code: "CR",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/f2/Flag_of_Costa_Rica.svg",
    countryCode: "+506",
    phoneNumberLength: 8,
    nationality: "Costa Rican",
  },
  {
    name: "Cote D'Ivoire",
    code: "CI",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg",
    countryCode: "+225",
    phoneNumberLength: 8,
    nationality: "Ivorian",
  },
  {
    name: "Croatia",
    code: "HR",
    file_url: "//upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg",
    countryCode: "+385",
    phoneNumberLength: 8,
    nationality: "Croatian",
  },
  {
    name: "Cuba",
    code: "CU",
    file_url: "//upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg",
    countryCode: "+53",
    phoneNumberLength: 8,
    nationality: "Cuban",
  },
  {
    name: "Cyprus",
    code: "CY",
    file_url: "//upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg",
    countryCode: "+357",
    phoneNumberLength: 8,
    nationality: "Cypriot",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg",
    countryCode: "+420",
    phoneNumberLength: 9,
    nationality: "Czech",
  },
  {
    name: "Denmark",
    code: "DK",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg",
    countryCode: "+45",
    phoneNumberLength: 8,
    nationality: "Danish",
  },
  {
    name: "Djibouti",
    code: "DJ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_Djibouti.svg",
    countryCode: "+253",
    phoneNumberLength: 8,
    nationality: "Djiboutian",
  },
  {
    name: "Dominica",
    code: "DM",
    file_url: "//upload.wikimedia.org/wikipedia/commons/c/c4/Flag_of_Dominica.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Dominican",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Dominican",
  },
  {
    name: "Ecuador",
    code: "EC",
    file_url: "//upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg",
    countryCode: "+593",
    phoneNumberLength: 9,
    nationality: "Ecuadorian",
  },
  {
    name: "Egypt",
    code: "EG",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg",
    countryCode: "+20",
    phoneNumberLength: 11,
    nationality: "Egyptian",
  },
  {
    name: "El Salvador",
    code: "SV",
    file_url: "//upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_El_Salvador.svg",
    countryCode: "+503",
    phoneNumberLength: 8,
    nationality: "Salvadoran",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Equatorial_Guinea.svg",
    countryCode: "+240",
    phoneNumberLength: 7,
    nationality: "Equatorial Guinean",
  },
  {
    name: "Eritrea",
    code: "ER",
    file_url: "//upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Eritrea.svg",
    countryCode: "+291",
    phoneNumberLength: 7,
    nationality: "Eritrean",
  },
  {
    name: "Estonia",
    code: "EE",
    file_url: "//upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg",
    countryCode: "+372",
    phoneNumberLength: 7,
    nationality: "Estonian",
  },
  {
    name: "Ethiopia",
    code: "ET",
    file_url: "//upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Ethiopia.svg",
    countryCode: "+251",
    phoneNumberLength: 9,
    nationality: "Ethiopian",
  },
  {
    name: "Falkland Islands (Malvinas)",
    code: "FK",
    file_url: "//upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_Falkland_Islands.svg",
    countryCode: "+500",
    phoneNumberLength: 5,
    nationality: "Falkland Islander",
  },
  {
    name: "Faroe Islands",
    code: "FO",
    file_url: "//upload.wikimedia.org/wikipedia/commons/3/3c/Flag_of_the_Faroe_Islands.svg",
    countryCode: "+298",
    phoneNumberLength: 7,
    nationality: "Faroese",
  },
  {
    name: "Fiji",
    code: "FJ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Fiji.svg",
    countryCode: "+679",
    phoneNumberLength: 7,
    nationality: "Fijian",
  },
  {
    name: "Finland",
    code: "FI",
    file_url: "//upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg",
    countryCode: "+358",
    phoneNumberLength: 10,
    nationality: "Finnish",
  },
  {
    name: "France",
    code: "FR",
    file_url: "//upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg",
    countryCode: "+33",
    phoneNumberLength: 9,
    nationality: "French",
  },
  {
    name: "French Guiana",
    code: "GF",
    file_url: "//upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_French_Guiana.svg",
    countryCode: "+594",
    phoneNumberLength: 10,
    nationality: "French Guianese",
  },
  {
    name: "French Polynesia",
    code: "PF",
    file_url: "//upload.wikimedia.org/wikipedia/commons/d/db/Flag_of_French_Polynesia.svg",
    countryCode: "+689",
    phoneNumberLength: 6,
    nationality: "French Polynesian",
  },
  {
    name: "French Southern Territories",
    code: "TF",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/a/a7/Flag_of_the_French_Southern_and_Antarctic_Lands.svg",
    countryCode: "+262",
    phoneNumberLength: 0,
    nationality: null,
  },
  {
    name: "Gabon",
    code: "GA",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/04/Flag_of_Gabon.svg",
    countryCode: "+241",
    phoneNumberLength: 7,
    nationality: "Gabonese",
  },
  {
    name: "Gambia",
    code: "GM",
    file_url: "//upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_The_Gambia.svg",
    countryCode: "+220",
    phoneNumberLength: 7,
    nationality: "Gambian",
  },
  {
    name: "Georgia",
    code: "GE",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Georgia.svg",
    countryCode: "+995",
    phoneNumberLength: 9,
    nationality: "Georgian",
  },
  {
    name: "Germany",
    code: "DE",
    file_url: "//upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg",
    countryCode: "+49",
    phoneNumberLength: 11,
    nationality: "German",
  },
  {
    name: "Ghana",
    code: "GH",
    file_url: "//upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg",
    countryCode: "+233",
    phoneNumberLength: 10,
    nationality: "Ghanaian",
  },
  {
    name: "Gibraltar",
    code: "GI",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/02/Flag_of_Gibraltar.svg",
    countryCode: "+350",
    phoneNumberLength: 8,
    nationality: "Gibraltarian",
  },
  {
    name: "Greece",
    code: "GR",
    file_url: "//upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg",
    countryCode: "+30",
    phoneNumberLength: 10,
    nationality: "Greek",
  },
  {
    name: "Greenland",
    code: "GL",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_Greenland.svg",
    countryCode: "+299",
    phoneNumberLength: 6,
    nationality: "Greenlandic",
  },
  {
    name: "Grenada",
    code: "GD",
    file_url: "//upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Grenada.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Grenadian",
  },
  {
    name: "Guadeloupe",
    code: "GP",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/7/7d/Flag_of_Guadeloupe_%28local%29_variant.svg",
    countryCode: "+590",
    phoneNumberLength: 10,
    nationality: "Guadeloupean",
  },
  {
    name: "Guam",
    code: "GU",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/07/Flag_of_Guam.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Guamanian",
  },
  {
    name: "Guatemala",
    code: "GT",
    file_url: "//upload.wikimedia.org/wikipedia/commons/e/ec/Flag_of_Guatemala.svg",
    countryCode: "+502",
    phoneNumberLength: 8,
    nationality: "Guatemalan",
  },
  {
    name: "Guernsey",
    code: "GG",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Guernsey.svg",
    countryCode: "+44",
    phoneNumberLength: 11,
    nationality: "Channel Islander",
  },
  {
    name: "Guinea",
    code: "GN",
    file_url: "//upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Guinea.svg",
    countryCode: "+224",
    phoneNumberLength: 9,
    nationality: "Guinean",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Guinea-Bissau.svg",
    countryCode: "+245",
    phoneNumberLength: 7,
    nationality: "Bissau-Guinean",
  },
  {
    name: "Guyana",
    code: "GY",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_Guyana.svg",
    countryCode: "+592",
    phoneNumberLength: 7,
    nationality: "Guyanese",
  },
  {
    name: "Haiti",
    code: "HT",
    file_url: "//upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg",
    countryCode: "+509",
    phoneNumberLength: 8,
    nationality: "Haitian",
  },
  {
    name: "Heard Island and Mcdonald Islands",
    code: "HM",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/b/bb/Proposed_flag_of_Antarctica_%28Graham_Bartram%29.svg",
    countryCode: "+334",
    phoneNumberLength: 0,
    nationality: null,
  },
  {
    name: "Holy See (Vatican City State)",
    code: "VA",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/9c/Flag_map_of_Vatican_City.svg",
    countryCode: "+379",
    phoneNumberLength: 7,
    nationality: "Vatican",
  },
  {
    name: "Honduras",
    code: "HN",
    file_url: "//upload.wikimedia.org/wikipedia/commons/8/82/Flag_of_Honduras.svg",
    countryCode: "+504",
    phoneNumberLength: 8,
    nationality: "Honduran",
  },
  {
    name: "Hong Kong",
    code: "HK",
    file_url: "//upload.wikimedia.org/wikipedia/commons/5/5b/Flag_of_Hong_Kong.svg",
    countryCode: "+852",
    phoneNumberLength: 8,
    nationality: "Hong Kong",
  },
  {
    name: "Hungary",
    code: "HU",
    file_url: "//upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg",
    countryCode: "+36",
    phoneNumberLength: 9,
    nationality: "Hungarian",
  },
  {
    name: "Iceland",
    code: "IS",
    file_url: "//upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg",
    countryCode: "+354",
    phoneNumberLength: 7,
    nationality: "Icelander",
  },
  {
    name: "India",
    code: "IN",
    file_url: "//upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg",
    countryCode: "+91",
    phoneNumberLength: 10,
    nationality: "Indian",
  },
  {
    name: "Indonesia",
    code: "ID",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg",
    countryCode: "+62",
    phoneNumberLength: 11,
    nationality: "Indonesian",
  },
  {
    name: "Iran, Islamic Republic Of",
    code: "IR",
    file_url: "//upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg",
    countryCode: "+98",
    phoneNumberLength: 10,
    nationality: "Iranian",
  },
  {
    name: "Iraq",
    code: "IQ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Iraq.svg",
    countryCode: "+964",
    phoneNumberLength: 10,
    nationality: "Iraqi",
  },
  {
    name: "Ireland",
    code: "IE",
    file_url: "//upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg",
    countryCode: "+353",
    phoneNumberLength: 9,
    nationality: "Irish",
  },
  {
    name: "Isle of Man",
    code: "IM",
    file_url: "//upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_the_Isle_of_Man.svg",
    countryCode: "+44",
    phoneNumberLength: 11,
    nationality: "Manx",
  },
  {
    name: "Israel",
    code: "IL",
    file_url: "//upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg",
    countryCode: "+972",
    phoneNumberLength: 9,
    nationality: "Israeli",
  },
  {
    name: "Italy",
    code: "IT",
    file_url: "//upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg",
    countryCode: "+39",
    phoneNumberLength: 10,
    nationality: "Italian",
  },
  {
    name: "Jamaica",
    code: "JM",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Jamaican",
  },
  {
    name: "Japan",
    code: "JP",
    file_url: "//upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg",
    countryCode: "+81",
    phoneNumberLength: 10,
    nationality: "Japanese",
  },
  {
    name: "Jersey",
    code: "JE",
    file_url: "//upload.wikimedia.org/wikipedia/commons/1/1c/Flag_of_Jersey.svg",
    countryCode: "+44",
    phoneNumberLength: 11,
    nationality: "Jersey",
  },
  {
    name: "Jordan",
    code: "JO",
    file_url: "//upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg",
    countryCode: "+962",
    phoneNumberLength: 9,
    nationality: "Jordanian",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg",
    countryCode: "+7",
    phoneNumberLength: 10,
    nationality: "Kazakhstani",
  },
  {
    name: "Kenya",
    code: "KE",
    file_url: "//upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg",
    countryCode: "+254",
    phoneNumberLength: 10,
    nationality: "Kenyan",
  },
  {
    name: "Kiribati",
    code: "KI",
    file_url: "//upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kiribati.svg",
    countryCode: "+686",
    phoneNumberLength: 6,
    nationality: "I-Kiribati",
  },
  {
    name: "Korea, Democratic People'S Republic of",
    code: "KP",
    file_url: "//upload.wikimedia.org/wikipedia/commons/5/51/Flag_of_North_Korea.svg",
    countryCode: "+850",
    phoneNumberLength: 9,
    nationality: "North Korean",
  },
  {
    name: "Korea, Republic of",
    code: "KR",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg",
    countryCode: "+82",
    phoneNumberLength: 10,
    nationality: "South Korean",
  },
  {
    name: "Kuwait",
    code: "KW",
    file_url: "//upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Kuwait.svg",
    countryCode: "+965",
    phoneNumberLength: 8,
    nationality: "Kuwaiti",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    file_url: "//upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Kyrgyzstan.svg",
    countryCode: "+996",
    phoneNumberLength: 9,
    nationality: "Kyrgyzstani",
  },
  {
    name: "Lao People'S Democratic Republic",
    code: "LA",
    file_url: "//upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Laos.svg",
    countryCode: "+856",
    phoneNumberLength: 8,
    nationality: "Laotian",
  },
  {
    name: "Latvia",
    code: "LV",
    file_url: "//upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg",
    countryCode: "+371",
    phoneNumberLength: 8,
    nationality: "Latvian",
  },
  {
    name: "Lebanon",
    code: "LB",
    file_url: "//upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg",
    countryCode: "+961",
    phoneNumberLength: 8,
    nationality: "Lebanese",
  },
  {
    name: "Lesotho",
    code: "LS",
    file_url: "//upload.wikimedia.org/wikipedia/commons/4/4a/Flag_of_Lesotho.svg",
    countryCode: "+266",
    phoneNumberLength: 8,
    nationality: "Mosotho",
  },
  {
    name: "Liberia",
    code: "LR",
    file_url: "//upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Liberia.svg",
    countryCode: "+231",
    phoneNumberLength: 7,
    nationality: "Liberian",
  },
  {
    name: "Libyan Arab Jamahiriya",
    code: "LY",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Libya.svg",
    countryCode: "+218",
    phoneNumberLength: 9,
    nationality: "Libyan",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    file_url: "//upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Liechtenstein.svg",
    countryCode: "+423",
    phoneNumberLength: 8,
    nationality: "Liechtensteiner",
  },
  {
    name: "Lithuania",
    code: "LT",
    file_url: "//upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg",
    countryCode: "+370",
    phoneNumberLength: 8,
    nationality: "Lithuanian",
  },
  {
    name: "Luxembourg",
    code: "LU",
    file_url: "//upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Luxembourg.svg",
    countryCode: "+352",
    phoneNumberLength: 9,
    nationality: "Luxembourger",
  },
  {
    name: "Macao",
    code: "MO",
    file_url: "//upload.wikimedia.org/wikipedia/commons/6/63/Flag_of_Macau.svg",
    countryCode: "+853",
    phoneNumberLength: 8,
    nationality: "Macanese",
  },
  {
    name: "Macedonia, The Former Yugoslav Republic of",
    code: "MK",
    file_url: "//upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_North_Macedonia.svg",
    countryCode: "+389",
    phoneNumberLength: 8,
    nationality: "Macedonian",
  },
  {
    name: "Madagascar",
    code: "MG",
    file_url: "//upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Madagascar.svg",
    countryCode: "+261",
    phoneNumberLength: 9,
    nationality: "Malagasy",
  },
  {
    name: "Malawi",
    code: "MW",
    file_url: "//upload.wikimedia.org/wikipedia/commons/d/d1/Flag_of_Malawi.svg",
    countryCode: "+265",
    phoneNumberLength: 9,
    nationality: "Malawian",
  },
  {
    name: "Maldives",
    code: "MV",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Maldives.svg",
    countryCode: "+960",
    phoneNumberLength: 7,
    nationality: "Maldivian",
  },
  {
    name: "Mali",
    code: "ML",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Mali.svg",
    countryCode: "+223",
    phoneNumberLength: 8,
    nationality: "Malian",
  },
  {
    name: "Malta",
    code: "MT",
    file_url: "//upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Malta.svg",
    countryCode: "+356",
    phoneNumberLength: 8,
    nationality: "Maltese",
  },
  {
    name: "Marshall Islands",
    code: "MH",
    file_url: "//upload.wikimedia.org/wikipedia/commons/2/2e/Flag_of_the_Marshall_Islands.svg",
    countryCode: "+692",
    phoneNumberLength: 7,
    nationality: "Marshallese",
  },
  {
    name: "Martinique",
    code: "MQ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/6/64/Snake_Flag_of_Martinique.svg",
    countryCode: "+596",
    phoneNumberLength: 10,
    nationality: "Martiniquais",
  },
  {
    name: "Mauritania",
    code: "MR",
    countryCode: "+222",
    file_url: "//upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Mauritania.svg",
    phoneNumberLength: 8,
    nationality: "Mauritanian",
  },
  {
    name: "Mauritius",
    code: "MU",
    file_url: "//upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Mauritius.svg",
    countryCode: "+230",
    phoneNumberLength: 7,
    nationality: "Mauritian",
  },
  {
    name: "Mayotte",
    code: "YT",
    file_url: "//upload.wikimedia.org/wikipedia/commons/4/4a/Flag_of_Mayotte_%28local%29.svg",
    countryCode: "+262",
    phoneNumberLength: 9,
    nationality: "Mahoran",
  },
  {
    name: "Mexico",
    code: "MX",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg",
    countryCode: "+52",
    phoneNumberLength: 10,
    nationality: "Mexican",
  },
  {
    name: "Micronesia, Federated States of",
    code: "FM",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg",
    countryCode: "+691",
    phoneNumberLength: 7,
    nationality: "Micronesian",
  },
  {
    name: "Moldova, Republic of",
    code: "MD",
    file_url: "//upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Moldova.svg",
    countryCode: "+373",
    phoneNumberLength: 8,
    nationality: "Moldovan",
  },
  {
    name: "Monaco",
    code: "MC",
    file_url: "//upload.wikimedia.org/wikipedia/commons/e/ea/Flag_of_Monaco.svg",
    countryCode: "+377",
    phoneNumberLength: 9,
    nationality: "Monegasque",
  },
  {
    name: "Mongolia",
    code: "MN",
    file_url: "//upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Mongolia.svg",
    countryCode: "+976",
    phoneNumberLength: 8,
    nationality: "Mongolian",
  },
  {
    name: "Montserrat",
    code: "MS",
    file_url: "//upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Montserrat.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Montserratian",
  },
  {
    name: "Morocco",
    code: "MA",
    file_url: "//upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg",
    countryCode: "+212",
    phoneNumberLength: 10,
    nationality: "Moroccan",
  },
  {
    name: "Mozambique",
    code: "MZ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Mozambique.svg",
    countryCode: "+258",
    phoneNumberLength: 9,
    nationality: "Mozambican",
  },
  {
    name: "Myanmar",
    code: "MM",
    file_url: "//upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Myanmar.svg",
    countryCode: "+95",
    phoneNumberLength: 9,
    nationality: "Burmese",
  },
  {
    name: "Namibia",
    code: "NA",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Namibia.svg",
    countryCode: "+264",
    phoneNumberLength: 9,
    nationality: "Namibian",
  },
  {
    name: "Nauru",
    code: "NR",
    file_url: "//upload.wikimedia.org/wikipedia/commons/3/30/Flag_of_Nauru.svg",
    countryCode: "+674",
    phoneNumberLength: 7,
    nationality: "Nauruan",
  },
  {
    name: "Nepal",
    code: "NP",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg",
    countryCode: "+977",
    phoneNumberLength: 10,
    nationality: "Nepali",
  },
  {
    name: "Netherlands",
    code: "NL",
    file_url: "//upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg",
    countryCode: "+31",
    phoneNumberLength: 10,
    nationality: "Dutch",
  },
  {
    name: "Netherlands Antilles",
    code: "AN",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/a/ae/Flag_of_the_Netherlands_Antilles_%281986%E2%80%932010%29.svg",
    countryCode: "+599",
    phoneNumberLength: 7,
    nationality: "Dutch Antillean",
  },
  {
    name: "New Caledonia",
    code: "NC",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/0/0c/Drapeau_de_Nouvelle-Cal%C3%A9donie.png",
    countryCode: "+687",
    phoneNumberLength: 6,
    nationality: "New Caledonian",
  },
  {
    name: "New Zealand",
    code: "NZ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg",
    countryCode: "+64",
    phoneNumberLength: 10,
    nationality: "New Zealander",
  },
  {
    name: "Nicaragua",
    code: "NI",
    file_url: "//upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Nicaragua.svg",
    countryCode: "+505",
    phoneNumberLength: 8,
    nationality: "Nicaraguan",
  },
  {
    name: "Niger",
    code: "NE",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/f4/Flag_of_Niger.svg",
    countryCode: "+227",
    phoneNumberLength: 8,
    nationality: "Nigerien",
  },
  {
    name: "Nigeria",
    code: "NG",
    file_url: "//upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg",
    countryCode: "+234",
    phoneNumberLength: 10,
    nationality: "Nigerian",
  },
  {
    name: "Niue",
    code: "NU",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Niue.svg",
    countryCode: "+683",
    phoneNumberLength: 4,
    nationality: "Niuean",
  },
  {
    name: "Norfolk Island",
    code: "NF",
    file_url: "//upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Norfolk_Island.svg",
    countryCode: "+672",
    phoneNumberLength: 5,
    nationality: "Norfolk Islander",
  },
  {
    name: "Northern Mariana Islands",
    code: "MP",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/e/e0/Flag_of_the_Northern_Mariana_Islands.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Northern Mariana Islander",
  },
  {
    name: "Norway",
    code: "NO",
    file_url: "//upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg",
    countryCode: "+47",
    phoneNumberLength: 8,
    nationality: "Norwegian",
  },
  {
    name: "Oman",
    code: "OM",
    file_url: "//upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Oman.svg",
    countryCode: "+968",
    phoneNumberLength: 8,
    nationality: "Omani",
  },
  {
    name: "Pakistan",
    code: "PK",
    file_url: "//upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg",
    countryCode: "+92",
    phoneNumberLength: 10,
    nationality: "Pakistani",
  },
  {
    name: "Palau",
    code: "PW",
    file_url: "//upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Palau.svg",
    countryCode: "+680",
    phoneNumberLength: 7,
    nationality: "Palauan",
  },
  {
    name: "Palestinian Territory, Occupied",
    code: "PS",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Palestine.svg",
    countryCode: "+970",
    phoneNumberLength: 9,
    nationality: "Palestinian",
  },
  {
    name: "Panama",
    code: "PA",
    file_url: "//upload.wikimedia.org/wikipedia/commons/a/ab/Flag_of_Panama.svg",
    countryCode: "+507",
    phoneNumberLength: 8,
    nationality: "Panamanian",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    file_url: "//upload.wikimedia.org/wikipedia/commons/e/e3/Flag_of_Papua_New_Guinea.svg",
    countryCode: "+675",
    phoneNumberLength: 7,
    nationality: "Papua New Guinean",
  },
  {
    name: "Paraguay",
    code: "PY",
    file_url: "//upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Paraguay.svg",
    countryCode: "+595",
    phoneNumberLength: 9,
    nationality: "Paraguayan",
  },
  {
    name: "Peru",
    code: "PE",
    file_url: "//upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Peru.svg",
    countryCode: "+51",
    phoneNumberLength: 9,
    nationality: "Peruvian",
  },
  {
    name: "Philippines",
    code: "PH",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg",
    countryCode: "+63",
    phoneNumberLength: 10,
    nationality: "Filipino",
  },
  {
    name: "Pitcairn",
    code: "PN",
    file_url: "//upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_the_Pitcairn_Islands.svg",
    countryCode: "+64",
    phoneNumberLength: 10,
    nationality: "Pitcairn Islander",
  },
  {
    name: "Poland",
    code: "PL",
    file_url: "//upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg",
    countryCode: "+48",
    phoneNumberLength: 9,
    nationality: "Polish",
  },
  {
    name: "Portugal",
    code: "PT",
    file_url: "//upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg",
    countryCode: "+351",
    phoneNumberLength: 9,
    nationality: "Portuguese",
  },
  {
    name: "Puerto Rico",
    code: "PR",
    file_url: "//upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_Puerto_Rico.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Puerto Rican",
  },
  {
    name: "Qatar",
    code: "QA",
    file_url: "//upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg",
    countryCode: "+974",
    phoneNumberLength: 8,
    nationality: "Qatari",
  },
  {
    name: "Reunion",
    code: "RE",
    file_url: "//upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg",
    countryCode: "+262",
    phoneNumberLength: 9,
    nationality: "Réunionese",
  },
  {
    name: "Romania",
    code: "RO",
    file_url: "//upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg",
    countryCode: "+40",
    phoneNumberLength: 10,
    nationality: "Romanian",
  },
  {
    name: "Russian Federation",
    code: "RU",
    file_url: "//upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg",
    countryCode: "+7",
    phoneNumberLength: 10,
    nationality: "Russian",
  },
  {
    name: "RWANDA",
    code: "RW",
    file_url: "//upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Rwanda.svg",
    countryCode: "+250",
    phoneNumberLength: 9,
    nationality: "Rwandan",
  },
  {
    name: "Saint Helena",
    code: "SH",
    file_url: "//upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg",
    countryCode: "+290",
    phoneNumberLength: 6,
    nationality: "Saint Helenian",
  },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Kittitian/Nevisian",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Saint_Lucia.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Saint Lucian",
  },
  {
    name: "Saint Martin (French part)",
    code: "MAF",
    file_url: "//upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg",
    countryCode: "+508",
    phoneNumberLength: 6,
    nationality: "Saint-Martinoise",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Saint Vincentian",
  },
  {
    name: "Samoa",
    code: "WS",
    file_url: "//upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Samoa.svg",
    countryCode: "+685",
    phoneNumberLength: 7,
    nationality: "Samoan",
  },
  {
    name: "San Marino",
    code: "SM",
    file_url: "//upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_San_Marino.svg",
    countryCode: "+378",
    phoneNumberLength: 8,
    nationality: "Sammarinese",
  },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg",
    countryCode: "+239",
    phoneNumberLength: 7,
    nationality: "São Toméan",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg",
    countryCode: "+966",
    phoneNumberLength: 9,
    nationality: "Saudi Arabian",
  },
  {
    name: "Senegal",
    code: "SN",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Senegal.svg",
    countryCode: "+221",
    phoneNumberLength: 9,
    nationality: "Senegalese",
  },
  {
    name: "Serbia and Montenegro",
    code: "CS",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg",
    countryCode: "+381",
    phoneNumberLength: 9,
    nationality: "Serbian",
  },
  {
    name: "Seychelles",
    code: "SC",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Seychelles.svg",
    countryCode: "+248",
    phoneNumberLength: 7,
    nationality: "Seychellois",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    file_url: "//upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Sierra_Leone.svg",
    countryCode: "+232",
    phoneNumberLength: 8,
    nationality: "Sierra Leonean",
  },
  {
    name: "Singapore",
    code: "SG",
    file_url: "//upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg",
    countryCode: "+65",
    phoneNumberLength: 8,
    nationality: "Singaporean",
  },
  {
    name: "Slovakia",
    code: "SK",
    file_url: "//upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg",
    countryCode: "+421",
    phoneNumberLength: 9,
    nationality: "Slovak",
  },
  {
    name: "Slovenia",
    code: "SI",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Slovenia.svg",
    countryCode: "+386",
    phoneNumberLength: 8,
    nationality: "Slovene",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    file_url: "//upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Solomon_Islands.svg",
    countryCode: "+677",
    phoneNumberLength: 7,
    nationality: "Solomon Islander",
  },
  {
    name: "Somalia",
    code: "SO",
    file_url: "//upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Somalia.svg",
    countryCode: "+252",
    phoneNumberLength: 8,
    nationality: "Somali",
  },
  {
    name: "South Africa",
    code: "ZA",
    file_url: "//upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg",
    countryCode: "+27",
    phoneNumberLength: 9,
    nationality: "South African",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    code: "GS",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_South_Georgia_and_the_South_Sandwich_Islands.svg",
    countryCode: "+500",
    phoneNumberLength: 0,
    nationality: "South Georgian",
  },
  {
    name: "Spain",
    code: "ES",
    file_url: "//upload.wikimedia.org/wikipedia/commons/8/89/Bandera_de_Espa%C3%B1a.svg",
    countryCode: "+34",
    phoneNumberLength: 9,
    nationality: "Spanish",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    file_url: "//upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg",
    countryCode: "+94",
    phoneNumberLength: 9,
    nationality: "Sri Lankan",
  },
  {
    name: "Sudan",
    code: "SD",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Sudan.svg",
    countryCode: "+249",
    phoneNumberLength: 9,
    nationality: "Sudanese",
  },
  {
    name: "Suriname",
    code: "SR",
    file_url: "//upload.wikimedia.org/wikipedia/commons/6/60/Flag_of_Suriname.svg",
    countryCode: "+597",
    phoneNumberLength: 7,
    nationality: "Surinamese",
  },
  {
    name: "Svalbard and Jan Mayen",
    code: "SJ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg",
    countryCode: "+47",
    phoneNumberLength: 8,
    nationality: "Norwegian",
  },
  {
    name: "Swaziland",
    code: "SZ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/fb/Flag_of_Eswatini.svg",
    countryCode: "+268",
    phoneNumberLength: 8,
    nationality: "Swazi",
  },
  {
    name: "Sweden",
    code: "SE",
    file_url: "//upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg",
    countryCode: "+46",
    phoneNumberLength: 9,
    nationality: "Swedish",
  },
  {
    name: "Switzerland",
    code: "CH",
    file_url: "//upload.wikimedia.org/wikipedia/commons/5/53/Flag_of_Syria.svg",
    countryCode: "+41",
    phoneNumberLength: 9,
    nationality: "Swiss",
  },
  {
    name: "Syrian Arab Republic",
    code: "SY",
    file_url: "//upload.wikimedia.org/wikipedia/commons/5/53/Flag_of_Syria.svg",
    countryCode: "+963",
    phoneNumberLength: 10,
    nationality: "Syrian",
  },
  {
    name: "Taiwan",
    code: "TW",
    file_url: "//upload.wikimedia.org/wikipedia/commons/7/72/Flag_of_the_Republic_of_China.svg",
    countryCode: "+886",
    phoneNumberLength: 9,
    nationality: "Taiwanese",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Tajikistan.svg",
    countryCode: "+992",
    phoneNumberLength: 9,
    nationality: "Tajik",
  },
  {
    name: "Tanzania, United Republic of",
    code: "TZ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tanzania.svg",
    countryCode: "+255",
    phoneNumberLength: 10,
    nationality: "Tanzanian",
  },
  {
    name: "Thailand",
    code: "TH",
    file_url: "//upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg",
    countryCode: "+66",
    phoneNumberLength: 9,
    nationality: "Thai",
  },
  {
    name: "Timor-Leste",
    code: "TL",
    file_url: "//upload.wikimedia.org/wikipedia/commons/2/26/Flag_of_East_Timor.svg",
    countryCode: "+670",
    phoneNumberLength: 7,
    nationality: "East Timorese",
  },
  {
    name: "Togo",
    code: "TG",
    file_url: "//upload.wikimedia.org/wikipedia/commons/6/68/Flag_of_Togo.svg",
    countryCode: "+228",
    phoneNumberLength: 8,
    nationality: "Togolese",
  },
  {
    name: "Tokelau",
    code: "TK",
    file_url: "//upload.wikimedia.org/wikipedia/commons/8/8e/Flag_of_Tokelau.svg",
    countryCode: "+690",
    phoneNumberLength: 4,
    nationality: "Tokelauan",
  },
  {
    name: "Tonga",
    code: "TO",
    file_url: "//upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Tonga.svg",
    countryCode: "+676",
    phoneNumberLength: 5,
    nationality: "Tongan",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    file_url: "//upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Trinidad_and_Tobago.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Trinidadian/Tobagonian",
  },
  {
    name: "Tunisia",
    code: "TN",
    file_url: "//upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg",
    countryCode: "+216",
    phoneNumberLength: 8,
    nationality: "Tunisian",
  },
  {
    name: "Turkey",
    code: "TR",
    file_url: "//upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
    countryCode: "+90",
    phoneNumberLength: 10,
    nationality: "Turkish",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    file_url: "//upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Turkmenistan.svg",
    countryCode: "+993",
    phoneNumberLength: 8,
    nationality: "Turkmen",
  },
  {
    name: "Turks and Caicos Islands",
    code: "TC",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "Turks and Caicos Islander",
  },
  {
    name: "Tuvalu",
    code: "TV",
    file_url: "//upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tuvalu.svg",
    countryCode: "+688",
    phoneNumberLength: 5,
    nationality: "Tuvaluan",
  },
  {
    name: "Uganda",
    code: "UG",
    file_url: "//upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Uganda.svg",
    countryCode: "+256",
    phoneNumberLength: 9,
    nationality: "Ugandan",
  },
  {
    name: "Ukraine",
    code: "UA",
    file_url: "//upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg",
    countryCode: "+380",
    phoneNumberLength: 9,
    nationality: "Ukrainian",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    file_url: "//upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg",
    countryCode: "+971",
    phoneNumberLength: 9,
    nationality: "Emirati",
  },
  {
    name: "United Kingdom",
    code: "GB",
    file_url: "//upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg",
    countryCode: "+44",
    phoneNumberLength: 10,
    nationality: "British",
  },
  {
    name: "United States",
    code: "US",
    file_url: "//upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "American",
  },
  {
    name: "United States Minor Outlying Islands",
    code: "UM",
    file_url: "//upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "American",
  },
  {
    name: "Uruguay",
    code: "UY",
    file_url: "//upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg",
    countryCode: "+598",
    phoneNumberLength: 8,
    nationality: "Uruguayan",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    file_url: "//upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Uzbekistan.svg",
    countryCode: "+998",
    phoneNumberLength: 9,
    nationality: "Uzbekistani",
  },
  {
    name: "Vanuatu",
    code: "VU",
    file_url: "//upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg",
    countryCode: "+678",
    phoneNumberLength: 7,
    nationality: "Ni-Vanuatu",
  },
  {
    name: "Venezuela",
    code: "VE",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Venezuela.svg",
    countryCode: "+58",
    phoneNumberLength: 10,
    nationality: "Venezuelan",
  },
  {
    name: "VietNam",
    code: "VN",
    file_url: "//upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg",
    countryCode: "+84",
    phoneNumberLength: 9,
    nationality: "Vietnamese",
  },
  {
    name: "Virgin Islands, British",
    code: "VG",
    countryCode: "+1",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/4/42/Flag_of_the_British_Virgin_Islands.svg",
    phoneNumberLength: 10,
    nationality: "British Virgin Islander",
  },
  {
    name: "Virgin Islands, U.S.",
    code: "VI",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/f/f8/Flag_of_the_United_States_Virgin_Islands.svg",
    countryCode: "+1",
    phoneNumberLength: 10,
    nationality: "U.S. Virgin Islander",
  },
  {
    name: "Wallis and Futuna",
    code: "WF",
    file_url: "//upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg",
    countryCode: "+681",
    phoneNumberLength: 6,
    nationality: "Wallis and Futuna",
  },
  {
    name: "Western Sahara",
    code: "EH",
    file_url:
      "//upload.wikimedia.org/wikipedia/commons/2/26/Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg",
    countryCode: "+212",
    phoneNumberLength: 9,
    nationality: "Sahrawi",
  },
  {
    name: "Yemen",
    code: "YE",
    file_url: "//upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Yemen.svg",
    countryCode: "+967",
    phoneNumberLength: 9,
    nationality: "Yemeni",
  },
  {
    name: "Zambia",
    code: "ZM",
    file_url: "//upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Zambia.svg",
    countryCode: "+260",
    phoneNumberLength: 9,
    nationality: "Zambian",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    file_url: "//upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg",
    countryCode: "+263",
    phoneNumberLength: 9,
    nationality: "Zimbabwean",
  },
];
